name: tcprcon
services:
  mh-server:
    image: ghcr.io/gameservermanagers/gameserver:mh
    container_name: mhserver
    ports:
      - "7778:7778"
      - "7777:7777"
      - "7780:7780"
      - "15000:15000"
      - "27015:27015"
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "12512"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - linuxgsm-mh:/data
      - .serverdata/mh/common.cfg:/data/config-lgsm/mhserver/common.cfg
      - .serverdata/mh/Game.ini:/data/serverfiles/Mordhau/Saved/Config/LinuxServer/Game.ini

volumes:
  linuxgsm-mh:
