name: tcprcon
services:
  cli:
    container_name: cli
    build: .
    mh-server:
      condition: service_healthy
      restart: true

  mh-server:
    image: ghcr.io/gameservermanagers/gameserver:mh
    container_name: mhserver
    ports:
      - "7778:7778"
      - "7777:7777"
      - "7780:7780"
      - "15000:15000"
      - "27015:27015"
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-w 5", "localhost 7777"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - linuxgsm-mh:/data
      - .serverdata/common.cfg:/data/config-lgsm/mhserver/common.cfg
      - .serverdata/Game.ini:/data/serverfiles/Mordhau/Saved/Config/LinuxServer/Game.ini

volumes:
  linuxgsm-mh:
